export const caseStudies = [
  {
    slug: 'clinical-data-platform-lakehouse',
    track: 'enterprise',
    industry: 'Pharma · Data Engineering',
    title: 'Clinical data platform on the lakehouse',
    summary: 'Migrated fragmented trial data into a governed lakehouse with automated ingestion and quality checks, giving analysts a single validated source.',
    meta: [
      { k: 'Timeline', v: '16 wks' },
      { k: 'Pipelines', v: '40+' },
      { k: 'Load time', v: '−70%' },
    ],
    href: '/case-studies/clinical-data-platform-lakehouse',
  },
  {
    slug: 'on-prem-to-cloud-zero-downtime',
    track: 'enterprise',
    industry: 'Retail · Cloud Migration',
    title: 'On-prem warehouse to cloud, zero downtime',
    summary: 'Replatformed a legacy on-prem data warehouse to the cloud with phased cutover, parallel validation, and no interruption to daily reporting.',
    meta: [
      { k: 'Workloads', v: '120' },
      { k: 'Downtime', v: '0 hrs' },
      { k: 'Infra cost', v: '−35%' },
    ],
    href: '/case-studies/on-prem-to-cloud-zero-downtime',
  },
  {
    slug: 'business-process-design-ai',
    track: 'solo',
    industry: 'Startup · AI Automation',
    title: 'Business process design with AI built in',
    summary: 'Designed the operating workflows for a growing startup — roles, reporting, and feedback loops — with AI agents handling intake, triage, and follow-ups.',
    meta: [
      { k: 'Processes', v: '8' },
      { k: 'Manual work', v: '−60%' },
      { k: 'Go-live', v: '6 wks' },
    ],
    href: '/case-studies/business-process-design-ai',
  },
  {
    slug: 'whatsapp-linkedin-outreach-console',
    track: 'solo',
    industry: 'Services · Customer Outreach',
    title: 'WhatsApp + LinkedIn outreach console',
    summary: 'Replaced spreadsheet-based follow-up with a segmented outreach console spanning WhatsApp, LinkedIn, and email — with response tracking by owner.',
    meta: [
      { k: 'Channels', v: '3' },
      { k: 'Response rate', v: '+2.1x' },
      { k: 'Go-live', v: '5 wks' },
    ],
    href: '/case-studies/whatsapp-linkedin-outreach-console',
  },
  {
    slug: 'campaign-reporting-real-conversions',
    track: 'solo',
    industry: 'E-commerce · Performance Marketing',
    title: 'Campaign reporting tied to real conversions',
    summary: 'Connected ad spend, landing pages, and CRM data into one funnel view, replacing disconnected platform dashboards with a single source of truth.',
    meta: [
      { k: 'Channels tracked', v: '6' },
      { k: 'CAC', v: '−22%' },
      { k: 'Reporting', v: 'Daily' },
    ],
    href: '/case-studies/campaign-reporting-real-conversions',
  },
  {
    slug: 'cutting-delivery-cost-without-cutting-scope',
    track: 'enterprise',
    industry: 'Manufacturing · Cost Optimization',
    title: 'Cutting delivery cost without cutting scope',
    summary: 'Reviewed an in-flight cloud modernization plan and re-sequenced delivery phases to protect the highest-value features under a tighter budget.',
    meta: [
      { k: 'Budget saved', v: '−28%' },
      { k: 'Scope kept', v: '100%' },
      { k: 'Review time', v: '3 wks' },
    ],
    href: '/case-studies/cutting-delivery-cost-without-cutting-scope',
  },
];
