// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }





// src/app/layout.jsx
import Header from './components/header';
import Footer from './components/footer'
import './globals.css'    // Tailwind utilities and base styles

export const metadata = {
  title: 'TINITIATE',
  description: 'Empowering IT Careers',
  icons: {
    icon: '/favicon.png', // or .png/.svg
  },
}
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
         <head>
        <link rel="icon" type="image/png" href="/favicon.png" />
        
      </head>
      <body className="bg-white text-gray-900 flex flex-col min-h-screen">
        <header className="fixed top-0 left-0 w-full z-[1000] bg-white ">
          <Header />
        </header>
        <main className="flex-grow pt-14">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  )
}
